# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChatBot(object):
    def setupUi(self, ChatBot):
        ChatBot.setObjectName("ChatBot")
        ChatBot.resize(543, 392)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../2.0/icons8-chatgpt_1.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ChatBot.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(ChatBot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("QWidget {\n"
"background-color: #ffffff;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_frame.sizePolicy().hasHeightForWidth())
        self.main_frame.setSizePolicy(sizePolicy)
        self.main_frame.setStyleSheet("QFrame {\n"
"background-color: #ffffff;\n"
"}\n"
"")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_frame.sizePolicy().hasHeightForWidth())
        self.button_frame.setSizePolicy(sizePolicy)
        self.button_frame.setStyleSheet("QFrame {\n"
"background-color: #f0f0f0;\n"
"border-radius: 14px;\n"
"\n"
"}\n"
"")
        self.button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.button_frame.setObjectName("button_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.button_frame)
        self.verticalLayout_2.setContentsMargins(1, 0, 1, 19)
        self.verticalLayout_2.setSpacing(11)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("border-image: url(:/img/ChatGPT_logo.svg.png);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(5)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2.addWidget(self.frame_2)
        self.chButton_1 = QtWidgets.QPushButton(self.button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.chButton_1.sizePolicy().hasHeightForWidth())
        self.chButton_1.setSizePolicy(sizePolicy)
        self.chButton_1.setStyleSheet("QPushButton {\n"
"    background-color: #1e6fff;\n"
"    border-radius: 10px;\n"
"    font:10pt \"Microsoft YaHei UI\";\n"
"    color: #ffffff;    \n"
"}\n"
"QPushButton:hover {\n"
"    font:10pt \"Microsoft YaHei UI\";\n"
"    background-color: #5391ff;\n"
"    border-radius: 10px;\n"
"    color: #ffffff;    \n"
"}\n"
"QPushButton:pressed {\n"
"    font:10pt \"Microsoft YaHei UI\";\n"
"    background-color: #1b65eb;\n"
"    border-radius: 10px;\n"
"    color: #ffffff;    \n"
"}")
        self.chButton_1.setObjectName("chButton_1")
        self.verticalLayout_2.addWidget(self.chButton_1)
        self.chButton_2 = QtWidgets.QPushButton(self.button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.chButton_2.sizePolicy().hasHeightForWidth())
        self.chButton_2.setSizePolicy(sizePolicy)
        self.chButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #1e6fff;\n"
"    border-radius: 10px;\n"
"    font:10pt \"Microsoft YaHei UI\";\n"
"    color: #ffffff;    \n"
"}\n"
"QPushButton:hover {\n"
"    font:10pt \"Microsoft YaHei UI\";\n"
"    background-color: #5391ff;\n"
"    border-radius: 10px;\n"
"    color: #ffffff;    \n"
"}\n"
"QPushButton:pressed {\n"
"    font:10pt \"Microsoft YaHei UI\";\n"
"    background-color: #1b65eb;\n"
"    border-radius: 10px;\n"
"    color: #ffffff;    \n"
"}")
        self.chButton_2.setObjectName("chButton_2")
        self.verticalLayout_2.addWidget(self.chButton_2)
        self.chButton_3 = QtWidgets.QPushButton(self.button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.chButton_3.sizePolicy().hasHeightForWidth())
        self.chButton_3.setSizePolicy(sizePolicy)
        self.chButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #1e6fff;\n"
"    border-radius: 10px;\n"
"    font:10pt \"Microsoft YaHei UI\";\n"
"    color: #ffffff;    \n"
"}\n"
"QPushButton:hover {\n"
"    font:10pt \"Microsoft YaHei UI\";\n"
"    background-color: #5391ff;\n"
"    border-radius: 10px;\n"
"    color: #ffffff;    \n"
"}\n"
"QPushButton:pressed {\n"
"    font:10pt \"Microsoft YaHei UI\";\n"
"    background-color: #1b65eb;\n"
"    border-radius: 10px;\n"
"    color: #ffffff;    \n"
"}")
        self.chButton_3.setObjectName("chButton_3")
        self.verticalLayout_2.addWidget(self.chButton_3)
        self.chButton_4 = QtWidgets.QPushButton(self.button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.chButton_4.sizePolicy().hasHeightForWidth())
        self.chButton_4.setSizePolicy(sizePolicy)
        self.chButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #1e6fff;\n"
"    border-radius: 10px;\n"
"    font:10pt \"Microsoft YaHei UI\";\n"
"    color: #ffffff;    \n"
"}\n"
"QPushButton:hover {\n"
"    font:10pt \"Microsoft YaHei UI\";\n"
"    background-color: #5391ff;\n"
"    border-radius: 10px;\n"
"    color: #ffffff;    \n"
"}\n"
"QPushButton:pressed {\n"
"    font:10pt \"Microsoft YaHei UI\";\n"
"    background-color: #1b65eb;\n"
"    border-radius: 10px;\n"
"    color: #ffffff;    \n"
"}")
        self.chButton_4.setObjectName("chButton_4")
        self.verticalLayout_2.addWidget(self.chButton_4)
        self.chButton_5 = QtWidgets.QPushButton(self.button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.chButton_5.sizePolicy().hasHeightForWidth())
        self.chButton_5.setSizePolicy(sizePolicy)
        self.chButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #1e6fff;\n"
"    border-radius: 10px;\n"
"    font:10pt \"Microsoft YaHei UI\";\n"
"    color: #ffffff;    \n"
"}\n"
"QPushButton:hover {\n"
"    font:10pt \"Microsoft YaHei UI\";\n"
"    background-color: #5391ff;\n"
"    border-radius: 10px;\n"
"    color: #ffffff;    \n"
"}\n"
"QPushButton:pressed {\n"
"    font:10pt \"Microsoft YaHei UI\";\n"
"    background-color: #1b65eb;\n"
"    border-radius: 10px;\n"
"    color: #ffffff;    \n"
"}")
        self.chButton_5.setObjectName("chButton_5")
        self.verticalLayout_2.addWidget(self.chButton_5)
        self.chButton_6 = QtWidgets.QPushButton(self.button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.chButton_6.sizePolicy().hasHeightForWidth())
        self.chButton_6.setSizePolicy(sizePolicy)
        self.chButton_6.setStyleSheet("QPushButton {\n"
"    background-color: #1e6fff;\n"
"    border-radius: 10px;\n"
"    font:10pt \"Microsoft YaHei UI\";\n"
"    color: #ffffff;    \n"
"}\n"
"QPushButton:hover {\n"
"    font:10pt \"Microsoft YaHei UI\";\n"
"    background-color: #5391ff;\n"
"    border-radius: 10px;\n"
"    color: #ffffff;    \n"
"}\n"
"QPushButton:pressed {\n"
"    font:10pt \"Microsoft YaHei UI\";\n"
"    background-color: #1b65eb;\n"
"    border-radius: 10px;\n"
"    color: #ffffff;    \n"
"}")
        self.chButton_6.setObjectName("chButton_6")
        self.verticalLayout_2.addWidget(self.chButton_6)
        self.frame = QtWidgets.QFrame(self.button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2.addWidget(self.frame)
        self.savebutton = QtWidgets.QPushButton(self.button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.savebutton.sizePolicy().hasHeightForWidth())
        self.savebutton.setSizePolicy(sizePolicy)
        self.savebutton.setStyleSheet("QPushButton {\n"
"    font:12pt \"Microsoft YaHei UI\";\n"
"    background-color: #1e6fff;\n"
"    border-radius: 10px;\n"
"    color: #ffffff;    \n"
"}\n"
"QPushButton:hover {\n"
"    font:12pt \"Microsoft YaHei UI\";\n"
"    background-color: #5391ff;\n"
"    border-radius: 10px;\n"
"    color: #ffffff;    \n"
"}\n"
"QPushButton:pressed {\n"
"    font:12pt \"Microsoft YaHei UI\";\n"
"    background-color: #1b65eb;\n"
"    border-radius: 10px;\n"
"    color: #ffffff;    \n"
"}")
        self.savebutton.setObjectName("savebutton")
        self.verticalLayout_2.addWidget(self.savebutton)
        self.horizontalLayout.addWidget(self.button_frame)
        self.right_frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(14)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_frame.sizePolicy().hasHeightForWidth())
        self.right_frame.setSizePolicy(sizePolicy)
        self.right_frame.setStyleSheet("QFrame {\n"
"background-color: #ffffff;\n"
"}\n"
"")
        self.right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_frame.setObjectName("right_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.right_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_frame = QtWidgets.QFrame(self.right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.top_frame.sizePolicy().hasHeightForWidth())
        self.top_frame.setSizePolicy(sizePolicy)
        self.top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame.setObjectName("top_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.top_frame)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.top_frame)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.apikey_edit = QtWidgets.QLineEdit(self.top_frame)
        self.apikey_edit.setObjectName("apikey_edit")
        self.gridLayout_3.addWidget(self.apikey_edit, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.top_frame)
        self.text_frame = QtWidgets.QFrame(self.right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.text_frame.sizePolicy().hasHeightForWidth())
        self.text_frame.setSizePolicy(sizePolicy)
        self.text_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.text_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.text_frame.setObjectName("text_frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.text_frame)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.text_frame)
        self.plainTextEdit.setStyleSheet("QPlainTextEdit { \n"
"font:12pt \"Microsoft YaHei UI\";\n"
"}")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_4.addWidget(self.plainTextEdit, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.text_frame)
        self.entry_frame = QtWidgets.QFrame(self.right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.entry_frame.sizePolicy().hasHeightForWidth())
        self.entry_frame.setSizePolicy(sizePolicy)
        self.entry_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.entry_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.entry_frame.setObjectName("entry_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.entry_frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.entey_Edit = QtWidgets.QTextEdit(self.entry_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entey_Edit.sizePolicy().hasHeightForWidth())
        self.entey_Edit.setSizePolicy(sizePolicy)
        self.entey_Edit.setStyleSheet("QTextEdit { \n"
"font:12pt \"Microsoft YaHei UI\";\n"
"}")
        self.entey_Edit.setObjectName("entey_Edit")
        self.gridLayout_2.addWidget(self.entey_Edit, 0, 0, 1, 1)
        self.sendbutton = QtWidgets.QPushButton(self.entry_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendbutton.sizePolicy().hasHeightForWidth())
        self.sendbutton.setSizePolicy(sizePolicy)
        self.sendbutton.setStyleSheet("QPushButton {\n"
"    background-color: #1e6fff;\n"
"    font:10pt \"Microsoft YaHei UI\";\n"
"    color: #ffffff;    \n"
"\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: #5391ff;\n"
"}\n"
"QPushButton:pressed {\n"
"  background-color: #1b65eb;\n"
"}")
        self.sendbutton.setObjectName("sendbutton")
        self.gridLayout_2.addWidget(self.sendbutton, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.entry_frame)
        self.horizontalLayout.addWidget(self.right_frame)
        self.gridLayout.addWidget(self.main_frame, 0, 0, 1, 1)
        ChatBot.setCentralWidget(self.centralwidget)

        self.retranslateUi(ChatBot)
        QtCore.QMetaObject.connectSlotsByName(ChatBot)

    def retranslateUi(self, ChatBot):
        _translate = QtCore.QCoreApplication.translate
        ChatBot.setWindowTitle(_translate("ChatBot", "GPT-3.5对话程序"))
        self.chButton_1.setText(_translate("ChatBot", "角色1"))
        self.chButton_2.setText(_translate("ChatBot", "角色2"))
        self.chButton_3.setText(_translate("ChatBot", "角色3"))
        self.chButton_4.setText(_translate("ChatBot", "角色4"))
        self.chButton_5.setText(_translate("ChatBot", "角色5"))
        self.chButton_6.setText(_translate("ChatBot", "角色6"))
        self.savebutton.setText(_translate("ChatBot", "保存对话"))
        self.label.setText(_translate("ChatBot", "API KEY:"))
        self.sendbutton.setText(_translate("ChatBot", "发送"))
import icon_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChatBot = QtWidgets.QMainWindow()
    ui = Ui_ChatBot()
    ui.setupUi(ChatBot)
    ChatBot.show()
    sys.exit(app.exec_())
